### ISSUE TITLE
Problem with mismatching answer and VN name, Gahkthun of the Golden Lightning

### ISSUE THREAD

**Issue by PedroOthinus** [mertvn/EMQ#52]
Below a print. 
Problem with mismatching japanese title of a VN and the answer in english. Happened on Gahkthun of the Golden Lightning.

If I do encounter more of this error, should I submit each individually or should I compile them on one big list before submiting?

https://imgur.com/bUaVLSX

**Comment by PedroOthinus** [comment]
Well, for some reason it didnt repeat itself on a subsequent playthrough.

https://imgur.com/WqKhztf

**Comment by mertvn** [comment]
That is very weird. Are you sure you guys didn't put a space before or after the VN name?

>If I do encounter more of this error, should I submit each individually or should I compile them on one big list before submiting?

You should submit them one by one under this issue.

**Comment by mertvn** [comment]
I couldn't reproduce this issue. It looks like the song stats were updated as though you were correct, so this is probably a client-server synchronization issue somehow. I've made a few improvements in that area since this issue was created, so hopefully it no longer happens. 
If you or anyone else ever encounters this issue again, please let me know.
